friend_avatar: /home/yxd/Desktop/head sculpture.jpg
my_avatar: /home/yxd/Desktop/wu.png
reminders:
- minutes: 30
  text: 该起来活动一下啦 🧘
  type: interval
server:
  host: 0.0.0.0
  port: 9000
target_ip: 127.0.0.1:9001
ui:
  bubble:
    font_size: 18
    max_width: 350
    padding: 12
  gif:
    max_height: 350
    max_width: 350
user_id: eb6d27b1b4874cb8a68edaf8c3422447
window:
  x: 200
  y: 100
